version: "3.9"

services:
  database:
    image: mysql:${DATABASE_VERSION}
    container_name: zabbix-database
    volumes:
      - database.data:/var/lib/mysql
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - TZ=${TIMEZONE}
    networks:
      - default
    restart: always
    command: --character-set-server=${DATABASE_CHARACTER_SET} --collation-server=${DATABASE_COLLATION} --default-authentication-plugin=mysql_native_password

  database-backup:
    image: ghcr.io/tiredofit/docker-db-backup:latest
    container_name: zabbix-database-backup
    volumes:
      - database-backup.data:/backup
    environment:
      - DB_TYPE=mysql
      - DB_HOST=database
      - DB_NAME=${DATABASE_NAME}
      - DB_USER=root
      - DB_PASS=${DATABASE_ROOT_PASSWORD}
      - DB_PORT=3306
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=2300
      - DB_DUMP_TARGET=/backup
      - DB_CLEANUP_TIME=43200
      - COMPRESSION=GZ
      - CREATE_LATEST_SYMLINK=false
      - CONTAINER_ENABLE_MONITORING=false
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-mysql:${ZABBIX_VERSION}
    container_name: zabbix-server
    ports:
      - 10050:10050
    volumes:
      - zabbix-server.alert-scripts:/usr/lib/zabbix/alertscripts
      - zabbix-server.external-scripts:/usr/lib/zabbix/externalscripts
      - zabbix-server.export:/var/lib/zabbix/export
      - zabbix-server.modules:/var/lib/zabbix/modules
      - zabbix-server.enc:/var/lib/zabbix/enc
      - zabbix-server.ssh-keys:/var/lib/zabbix/ssh_keys
      - zabbix-server.mibs:/var/lib/zabbix/mibs
      - zabbix-server.snmp-traps:/var/lib/zabbix/snmptraps
    environment:
      - DB_SERVER_HOST=database
      - DB_SERVER_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    networks:
      - default
    restart: always
    depends_on:
      - database

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:${ZABBIX_VERSION}
    container_name: zabbix-web
    volumes:
      - zabbix-web.ssl:/etc/ssl/nginx
    environment:
      - ZBX_SERVER_NAME=${ZABBIX_SERVER_NAME}
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
      - DB_SERVER_HOST=database
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - PHP_TZ=${TIMEZONE}
    labels:
      - traefik.enable=true
      - traefik.http.services.zabbix.loadbalancer.server.port=8080
      - traefik.http.routers.zabbix.rule=Host(`${ZABBIX_DOMAIN}`)
      - traefik.http.routers.zabbix.tls=true
    networks:
      - default
      - reverse-proxy-network
    restart: always
    depends_on:
      - database
      - zabbix-server

volumes:
  database.data:
  database-backup.data:
  zabbix-server.alert-scripts:
  zabbix-server.external-scripts:
  zabbix-server.export:
  zabbix-server.modules:
  zabbix-server.enc:
  zabbix-server.ssh-keys:
  zabbix-server.mibs:
  zabbix-server.snmp-traps:
  zabbix-web.ssl:

networks:
  reverse-proxy-network:
    external: true
  default:
    driver: bridge
    external: false
