version: "3.5"

services:
    percona-server:
        image: percona:8.0
        volumes:
            - percona-server.data:/var/lib/mysql
        environment:
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=
            - MYSQL_DATABASE=zabbix
            - MYSQL_ROOT_PASSWORD=
        networks:
            - default
        restart: always
        command: --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password

    zabbix-server:
        image: zabbix/zabbix-server-mysql:alpine-5.0-latest
        ports:
            - 10051:10051
        volumes:
            - zabbix-server.alert-scripts:/usr/lib/zabbix/alertscripts
            - zabbix-server.external-scripts:/usr/lib/zabbix/externalscripts
            - zabbix-server.export:/var/lib/zabbix/export
            - zabbix-server.modules:/var/lib/zabbix/modules
            - zabbix-server.enc:/var/lib/zabbix/enc
            - zabbix-server.ssh-keys:/var/lib/zabbix/ssh_keys
            - zabbix-server.mibs:/var/lib/zabbix/mibs
            - zabbix-server.snmp-traps:/var/lib/zabbix/snmptraps
        environment:
            - DB_SERVER_HOST=percona-server
            - DB_SERVER_PORT=3306
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=
            - MYSQL_DATABASE=zabbix
        networks:
            - default
        restart: always
        depends_on:
            - percona-server

    zabbix-web:
        image: zabbix/zabbix-web-nginx-mysql:alpine-5.0-latest
        ports:
            - 443:8443
        volumes:
            - zabbix-web.ssl:/etc/ssl/nginx
        environment:
            - ZBX_SERVER_HOST=zabbix-server
            - ZBX_SERVER_PORT=10051
            - DB_SERVER_HOST=percona-server
            - MYSQL_USER=zabbix
            - MYSQL_PASSWORD=
            - MYSQL_DATABASE=zabbix
            - PHP_TZ="Europe/Warsaw"
        networks:
            - default
        restart: always
        depends_on:
            - percona-server
            - zabbix-server

volumes:
    percona-server.data:
    zabbix-server.alert-scripts:
    zabbix-server.external-scripts:
    zabbix-server.export:
    zabbix-server.modules:
    zabbix-server.enc:
    zabbix-server.ssh-keys:
    zabbix-server.mibs:
    zabbix-server.snmp-traps:
    zabbix-web.ssl:

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.25.0.0/16
